import Foundation
import Testing
@testable import CowsayKit

/// Compatibility fixtures generated by cowsay 3.8.4.
///
/// Each expected file in `Golden/Expected/` is generated by `make golden`. Tests compare
/// `Data` rather than `String`, preserving trailing spaces, line endings, and invalid UTF-8
/// emitted when cowsay wraps through a multi-byte character. `.gitattributes` marks the
/// fixtures as binary so Git does not normalize them.
@Suite("Golden files")
struct GoldenTests {
    // MARK: Locating the repository

    /// Fixtures live in the source tree so the generator and tests use the same reviewable
    /// files.
    static let repositoryRoot: URL = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()   // CowsayKitTests
        .deletingLastPathComponent()   // Tests
        .deletingLastPathComponent()   // repo root

    static let goldenDirectory = repositoryRoot
        .appendingPathComponent("Tests/CowsayKitTests/Golden")

    // MARK: Manifest

    struct Case {
        let id: String
        let cow: String
        let mode: BalloonMode
        let flags: String
        let width: Int
        let messageCase: String

        /// `-n`: expand tabs, do not wrap.
        var noWrap: Bool { flags.split(separator: ",").contains("n") }

        var face: Face {
            guard flags != "-" else { return .default }
            var modes: Set<FaceMode> = []
            var eyes: ByteString?
            var tongue: ByteString?
            for token in flags.split(separator: ",") {
                if token.hasPrefix("eyes=") {
                    eyes = Bytes.from(String(token.dropFirst("eyes=".count)))
                } else if token.hasPrefix("tongue=") {
                    tongue = Bytes.from(String(token.dropFirst("tongue=".count)))
                } else if let first = token.first, let mode = FaceMode.fromFlag(first) {
                    modes.insert(mode)
                }
            }
            return Face.construct(customEyes: eyes, customTongue: tongue, modes: modes)
        }
    }

    static let cases: [Case] = {
        let manifest = goldenDirectory.appendingPathComponent("manifest.tsv")
        guard let text = try? String(contentsOf: manifest, encoding: .utf8) else { return [] }
        return text.split(separator: "\n").compactMap { line in
            let f = line.split(separator: "\t", omittingEmptySubsequences: false)
            guard f.count == 6, let width = Int(f[4]) else { return nil }
            return Case(
                id: String(f[0]), cow: String(f[1]),
                mode: f[2] == "think" ? .think : .say,
                flags: String(f[3]), width: width, messageCase: String(f[5])
            )
        }
    }()

    static let library = CowfileLibrary.load(
        directories: [repositoryRoot.appendingPathComponent("Resources/cows")]
    )

    // MARK: The test

    @Test func manifestIsPresentAndPopulated() {
        #expect(Self.cases.count > 150,
                "expected ~200 goldens; run `make golden`. Found \(Self.cases.count).")
    }

    @Test(arguments: GoldenTests.cases)
    func matchesRealCowsay(testCase: Case) throws {
        let cowfile = try #require(Self.library.cow(named: testCase.cow),
                                   "cowfile '\(testCase.cow)' failed to load")

        let messageURL = Self.goldenDirectory
            .appendingPathComponent("Cases/\(testCase.messageCase).txt")
        let expectedURL = Self.goldenDirectory
            .appendingPathComponent("Expected/\(testCase.id).out")

        let messageData = try Data(contentsOf: messageURL)
        let expected = try Data(contentsOf: expectedURL)

        let actual = Data(CowRenderer.render(CowsayRequest(
            message: Message.linesFromStdin(ByteString(messageData)),
            cowfile: cowfile,
            mode: testCase.mode,
            face: testCase.face,
            wrapColumns: testCase.width,
            noWrap: testCase.noWrap
        )))

        #expect(actual == expected, "\(testCase.id)\n\(Self.diff(actual: actual, expected: expected))")
    }

    /// Render a byte mismatch with visible whitespace and its first differing offset.
    static func diff(actual: Data, expected: Data) -> String {
        let a = ByteString(actual), e = ByteString(expected)
        let offset = zip(a, e).enumerated().first { $0.element.0 != $0.element.1 }?.offset
            ?? min(a.count, e.count)

        func context(_ bytes: ByteString) -> String {
            let start = bytes.index(bytes.startIndex, offsetBy: max(0, offset - 40))
            let end = bytes.index(bytes.startIndex, offsetBy: min(bytes.count, offset + 40))
            return visible(Array(bytes[start ..< end]))
        }

        return """
          first difference at byte \(offset) (actual \(a.count) bytes, expected \(e.count))
          actual:   …\(context(a))…
          expected: …\(context(e))…
        """
    }

    /// Spaces as `·`, tabs as `⇥`, newlines as `⏎`, anything non-printable as hex.
    static func visible(_ bytes: ByteString) -> String {
        bytes.map { byte in
            switch byte {
            case 0x20: return "·"
            case 0x09: return "⇥"
            case 0x0A: return "⏎"
            case 0x21...0x7E: return String(UnicodeScalar(byte))
            default: return String(format: "\\x%02X", byte)
            }
        }.joined()
    }
}

// swift-testing needs the parameter type to be sendable and identifiable for display.
extension GoldenTests.Case: CustomTestStringConvertible, Sendable {
    var testDescription: String { id }
}

// MARK: - Library-level invariants

@Suite("Bundled cowfiles")
struct BundledCowfileTests {
    private var library: CowfileLibrary { GoldenTests.library }

    @Test func loadsTheBundledCowfiles() {
        #expect(library.cows.count == 47,
                "expected 47 usable cowfiles of the 51 shipped, got \(library.cows.count)")
        #expect(library.cow(named: "stegosaurus") != nil, "stegosaurus is the requested pairing")
    }

    @Test func bundledCowfilesNeedNoParseFailures() {
        #expect(library.failures.isEmpty,
                "the bundled cowfile set should contain only statically parseable cowfiles")
    }

    /// The `##` headers carry artist attribution and must survive parsing.
    @Test func preservesAttributionHeaders() throws {
        let www = try String(
            contentsOf: GoldenTests.repositoryRoot
                .appendingPathComponent("Resources/cows/www.cow"),
            encoding: .utf8
        )
        #expect(www.contains("lim@csua.berkeley.edu"),
                "shipped cowfiles must keep their credit comments verbatim")

        let stegosaurus = try #require(library.cow(named: "stegosaurus"))
        #expect(stegosaurus.header.map(Bytes.describe)
                == ["##", "## A stegosaur with a top hat?", "##"])
    }
}

// MARK: - Built-in fallback

@Suite("Built-in fallback content")
struct BuiltInTests {
    /// Keep the compiled fallback cow aligned with its bundled source file.
    @Test func builtInCowMatchesTheBundledFile() throws {
        let bundled = try #require(GoldenTests.library.cow(named: "default"))
        let face = Face.construct(modes: [.tired])

        let fromFile = CowfileParser.render(bundled, thoughts: UInt8(ascii: "o"), face: face)
        let fromLiteral = CowfileParser.render(BuiltIn.defaultCow,
                                               thoughts: UInt8(ascii: "o"), face: face)

        #expect(fromLiteral == fromFile,
                "BuiltIn.defaultCowSource has drifted from Resources/cows/default.cow")
    }

    @Test func builtInDatabaseIsUsable() {
        let database = FortuneDatabase.builtIn()
        #expect(!database.isEmpty)
        #expect(database.fortunes.allSatisfy { FortuneDatabase.isSafe($0.text) })
        #expect(database.fortunes.allSatisfy { $0.text.utf8.count <= 500 })
    }

    /// The fallback renderer does not require resource directories.
    @Test func rendersWithNoResourcesPresent() {
        let empty = CowfileLibrary.load(directories: [URL(fileURLWithPath: "/nonexistent")])
        #expect(empty.isEmpty)

        var selector = NoRepeatSelector(database: .builtIn(), seed: 1, weightByFile: false)
        let fortune = selector.next()
        #expect(fortune != nil)

        let output = CowRenderer.render(message: fortune?.text ?? "", cowfile: BuiltIn.defaultCow)
        #expect(output.count > 50, "a fallback render must still produce a whole cow")
    }
}
